#!/bin/bash

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 4 -d " " | cut -c 1,2` < 15 ]] ; then

    DISPLAY=:0.0 /usr/bin/notify-send "low battery" "`echo $BATTINFO | cut -f 4 -d " " | cut -c 1,2,3` remaining"
fi
